import type { Metadata } from 'next'
import { useEffect } from 'react'
import { Inter } from 'next/font/google'
import './globals.css'
import { SocketProvider } from '@/context/SocketContext'
import { UserProvider, useUser } from '@/context/UserContext'
import { CheckSession } from '@/utils/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const { login } = useUser()

  useEffect(() => {
    const checkSession = async () => {
      let response = await CheckSession()
      if (response && response.status === 200) {
        let payload = response.data
        login(payload)
      }
    }
    checkSession()
  }, [])
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <SocketProvider>{children}</SocketProvider>
        </UserProvider>
      </body>
    </html>
  )
}
