import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import dynamic from 'next/dynamic'
import { SocketProvider } from '@/context/SocketContext'
import { UserProvider } from '@/context/UserContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const DynamicRedirect = dynamic(() => import('@/hooks/useRedirect'), {
  ssr: false
})

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <SocketProvider>
            <DynamicRedirect />
            {children}
          </SocketProvider>
        </UserProvider>
      </body>
    </html>
  )
}
